<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class HqsSeeder extends Seeder
{
    public function run(): void
    {
        // Limpar a tabela antes de inserir para evitar duplicados se o seeder for corrido múltiplas vezes
        DB::table('hqs')->truncate(); 

        DB::table('hqs')->insert([
            [
                'id' => 1,
                'titulo' => 'Invencível #144 - O fim de todas as coisas',
                'descricao' => 'Acompanha Mark Grayson, um adolescente que descobre ser filho de um super-herói e herda poderes fantásticos, enquanto navega por um mundo de super-heróis e enfrenta desafios pessoais e existenciais.',
                'generos' => 'Ação / Ficção Científica',
                'autor' => 'Robert Kirkman',
                'lancamento' => '2018-02-14',
                'imagens' => 'h1.webp',
                'link1' => 'https://www.amazon.com.br/Invincible-144-English-Robert-Kirkman-ebook/dp/B076HZQJHC#detailBullets_feature_div (Kindle, edição em inglês)',
                'link2' => 'https://books.apple.com/br/book/invincible-144/id1342767886 (Apple books, edição em inglês)',
                'link3' => null,
                'loja1' => 'Amazon',
                'loja2' => 'Apple Books',
                'loja3' => null,
            ],
            [
                'id' => 2,
                'titulo' => 'Homem-Aranha: Miles Morales #1',
                'descricao' => 'Quando o enfurecido Rino e um grupo de criminosos misteriosos começam a atormentar o Brooklyn, as coisas ficam feias para o jovem Homem-Aranha! Que mistérios o aguardam por trás deste novo levante de vilões? Por que o Rino tem lacaios? E quem é o novo antagonista que pode ter acabado de se tomar o inimigo mais poderoso de Miles? Talvez o Capitão América tenha as respostas! E mais: antes de vestir o uniforme, Miles Morales era apenas... Miles Morales: estudante recém-matriculado na Academia de Visões do Brooklyn com poderes de aranha secretos! Quando uma Invasão Secreta de Skrulls vira Manhattan ao avesso, Miles precisa escolher: seus grandes poderes vêm com grandes responsabilidades?',
                'generos' => 'Ação / Aventura',
                'autor' => 'Saladin Ahmed',
                'lancamento' => '2019-10-01',
                'imagens' => 'miles_morales_1.jpg',
                'link1' => 'https://www.amazon.com/Miles-Morales-Homem-Aranha-vol-Portuguese-ebook/dp/B08X8R6P3W?utm_source=chatgpt.com',
                'link2' => 'https://www.rika.com.br/miles-morales---homem-aranha--1---direto-do-brooklyn-15008013/p?srsltid=AfmBOoqWllP3tj702Owx1GnyacTxDxUZNZTa7MymSGPWbMDK_JqY6CfK&utm_source=chatgpt.com',
                'link3' => 'https://leitura.com.br/miles-morales-homem-aranha-vol-1-L030-9788542625615?srsltid=AfmBOooo30NbIrN-1dsFvEQAWoF1mEmwgtwhMlbHbgwlWkoRAhiJvhBa&utm_source=chatgpt.com',
                'loja1' => 'Amazon',
                'loja2' => 'Rika Comic Shop',
                'loja3' => 'Leitura',
            ],
            [
                'id' => 3,
                'titulo' => 'Batman: A piada mortal ',
                'descricao' => 'Do premiado roteirista Alan Moore (Watchmen, V de Vingança) conta como um dia ruim na vida de um homem pode significar a linha que separa a sanidade da loucura. Principalmente quando se trata do Coringa, o maior e mais conhecido vilão do mundo dos quadrinhos. Os desenhos de Brian Bolland (Camelot 3000), um dos maiores ilustradores dos quadrinhos, elevaram a história praticamente à perfeição retratando com maestria o mundo imaginado por Alan Moore. Mas faltava um detalhe para completar a obra. Bolland não pôde colorir a edição original, e agora, vinte anos depois, isso foi corrigido e as cores foram completamente refeitas pelo artista, seguindo fielmente a sua imaginação. Edição obrigatória para os fãs do Coringa, do Batman e dos quadrinhos.',
                'generos' => 'Drama / Crime',
                'autor' => 'Alan Moore',
                'lancamento' => '1988-03-29',
                'imagens' => 'joker.webp',
                'link1' => 'https://www.amazon.com.br/Batman-Piada-Mortal-Alan-Moore/dp/8573515473',
                'link2' => 'https://panini.com.br/batman-a-piada-mortal-edicao-absoluta?srsltid=AfmBOopo4V7D8Hz97xtl6GUtOgex_3_xgmRwnvq0to4zyOWCz_M_2yQP',
                'link3' => 'https://lista.mercadolivre.com.br/batman-a-piada-mortal-1988?utm_source=chatgpt.com',
                'loja1' => 'Amazon',
                'loja2' => 'Panini',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 4,
                'titulo' => 'Flash – A guerra dos gorilas',
                'descricao' => 'Descrição: Ele é conhecido como Rei Grodd, o implacável déspota de Gorilla City (lar de uma espécie superevoluída e hiperinteligente de símios). Acreditando ter sido escolhido para portar o poder da Força de Aceleração – a fonte das assombrosas habilidades do Flash –, Grodd está convicto de que o herói roubou seu direito de nascença… e veio com um exército para garantir que ele o devolva. E se uma cidade humana, e todos os seus habitantes, precisarem morrer no processo, que assim seja. Para deter essa que é a maior ameaça que já encarou, o Velocista Escarlate vai precisar se aliar a companheiros de batalha bem incomuns: a mesma Galeria de Vilões que ele vem enfrentando há anos! A vitória é incerta e virá a um alto custo. Mas, mesmo que chegue, pode significar apenas o prenúncio de uma batalha muito maior chegando no horizonte…',
                'generos' => 'Ação / Ficção Científica ',
                'autor' => 'Francis Manapul',
                'lancamento' => '2015-09-21',
                'imagens' => 'flash.jpg',
                'link1' => 'https://www.amazon.com.br/Flash-Guerra-Gorilas-Francis-Manapul/dp/8583681988',
                'link2' => 'https://www.lojascaverna.com.br/produtos/flash-a-guerra-dos-gorilas/',
                'link3' => 'https://produto.mercadolivre.com.br/MLB-2114494356-flash-a-guerra-dos-gorilas-panini-2016-capa-dura-_JM',
                'loja1' => 'Amazon',
                'loja2' => 'Lojas Caverna',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 5,
                'titulo' => 'Nêmesis ',
                'descricao' => 'O bilionário Matthew Anderson decidiu se tornar o maior supervilão do mundo. Com inteligência, tecnologia avançada e crueldade sem limites, ele desafia a lei e aterroriza os maiores detetives do planeta. Seu próximo alvo: o chefe de polícia Blake Morrow. Em uma caçada mortal, Nêmesis prova que, quando um gênio do crime está no controle, ninguém está seguro.',
                'generos' => 'Suspense / Terror',
                'autor' => 'Mark Millar',
                'lancamento' => '2010-06-24',
                'imagens' => 'hq8.png',
                'link1' => 'https://www.amazon.com.br/Nêmesis-1-Mark-Millar/dp/8565484394',
                'link2' => 'https://www.magazineluiza.com.br/hq-nemesis-panini/p/cd5jg675h3/li/hqlv/',
                'link3' => null,
                'loja1' => 'Amazon',
                'loja2' => 'Magazine Luiza',
                'loja3' => null,
            ],
            [
                'id' => 6,
                'titulo' => 'Justiceiro MAX #1 – No Princípio',
                'descricao' => 'Frank Castle, o Justiceiro, declara guerra total contra o crime organizado. Nesta HQ, ele enfrenta a poderosa família criminosa Gnucci enquanto lida com seu próprio passado sombrio. Com uma abordagem brutal e realista, essa história marca o início da icônica fase MAX, trazendo um Justiceiro mais violento e implacável do que nunca.',
                'generos' => 'Ação / Policial',
                'autor' => 'Garth Ennis',
                'lancamento' => '2018-06-22',
                'imagens' => 'justiceiro.jpg',
                'link1' => 'https://www.amazon.com.br/Justiceiro-No-Princípio-Garth-Ennis/dp/8583682941',
                'link2' => 'https://sp.olx.com.br/sao-paulo-e-regiao/livros-e-revistas/justiceiro-no-principio-edicao-deluxe-1403613891?lis=listing_no_category',
                'link3' => 'https://www.mercadolivre.com.br/justiceiro-no-principio-de-ennis-garth-editorial-panini-brasil-ltda-capa-dura-em-portugus-2018/p/MLB19223139',
                'loja1' => 'Amazon',
                'loja2' => 'Olx',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 7,
                'titulo' => 'Quarteto Fantástico - O fim',
                'descricao' => 'Num futuro distante, o Quarteto Fantástico é reverenciado por ter levado a humanidade a uma nova Era de Ouro. O sistema solar foi colonizado, mas há muito tempo a heroíca família debandou. Agora, um misterioso oponente do passado ameaça destruir tudo o que eles lutaram tanto para criar. O Quarteto precisará se reunir — não só pelo bem da família, mas pela sobrevivência de toda a galáxia. Este volume reúne as edições 1–6 de Fantastic Four: The End.',
                'generos' => 'Drama / Ficção Científica',
                'autor' => 'Alan Davis',
                'lancamento' => '2014-01-01',
                'imagens' => 'quarteto_fantastico.jpg',
                'link1' => 'https://www.amazon.com.br/Quarteto-Fant%C3%A1stico-Cole%C3%A7%C3%A3o-Oficial-Graphic/dp/B08W4PC598',
                'link2' => 'https://www.estantevirtual.com.br/busca/quarteto-fantastico-o-fim',
                'link3' => 'https://lista.mercadolivre.com.br/quarteto-fant%C3%A1stico-o-fim#D[A:quarteto%20fant%C3%A1stico%20o%20fim]',
                'loja1' => 'Amazon',
                'loja2' => 'Estante Virtual',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 8,
                'titulo' => 'Um Passeio no Inferno #1 – Início da Queda',
                'descricao' => 'Uma investigação do FBI sobre o desaparecimento de dois agentes os leva até um depósito sinistro ligado a um atentado terrorista. Lá, descobrem um homem envolvido com segredos obscuros e uma conspiração que vai além da compreensão. Terror psicológico, violência e tensão se misturam nessa HQ intensa escrita por Garth Ennis.',
                'generos' => 'Terror Psicológico / Drama',
                'autor' => 'Garth Ennis',
                'lancamento' => '2022-11-30',
                'imagens' => 'hq9.png',
                'link1' => 'https://www.amazon.com.br/Um-passeio-no-inferno-1/dp/8550820172',
                'link2' => 'https://www.ugrapress.com.br/produtos/um-passeio-no-inferno/',
                'link3' => 'https://www.mercadolivre.com.br/um-passeio-no-inferno-de-garth-ennis-editora-alta-geek-capa-mole-em-portugus-2022/p/MLB30580917',
                'loja1' => 'Amazon',
                'loja2' => 'Ugra Press',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 9,
                'titulo' => 'Watchmen - Edição Definitiva',
                'descricao' => 'Num mundo alternativo à beira da guerra nuclear, super-heróis são reais — mas falhos, corrompidos e perseguidos. Quando um ex-membro dos vigilantes mascarados é assassinado, uma conspiração vem à tona, revelando segredos obscuros e colocando o destino da humanidade em risco. Watchmen é uma narrativa densa e crítica sobre poder, moralidade e o verdadeiro significado do heroísmo.',
                'generos' => 'Drama',
                'autor' => 'Alan Moore',
                'lancamento' => '2022-03-04',
                'imagens' => 'watchmen.jpg',
                'link1' => 'https://www.amazon.com.br/Watchmen-V%C3%A1rios-Autores/dp/857351549X',
                'link2' => 'https://www.estantevirtual.com.br/livro/watchmen-edicao-definitiva-HNF-9043-000',
                'link3' => 'https://lista.mercadolivre.com.br/watchmen-edicao-definitiva',
                'loja1' => 'Amazon',
                'loja2' => 'Estante Virtual',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 10,
                'titulo' => 'Monstro do Pântano - Raízes do Mal | vol. 1',
                'descricao' => 'Após um trágico acidente, o cientista Alec Holland renasce como uma criatura elemental ligada à flora da Terra: o Monstro do Pântano. Nesta reinvenção revolucionária escrita por Alan Moore, a HQ mergulha em temas existenciais, terror e natureza, enquanto o Monstro descobre sua verdadeira origem e enfrenta ameaças sobrenaturais que desafiam a lógica humana.',
                'generos' => 'Terror / Suspense',
                'autor' => 'Alan Moore',
                'lancamento' => '2017-01-01',
                'imagens' => 'pântano.jpg',
                'link1' => 'https://www.amazon.com.br/Monstro-P%C3%A2ntano-Ra%C3%ADzes-Mal-Vol/dp/B07QZCTM31',
                'link2' => 'https://lista.mercadolivre.com.br/cl%C3%A1ssicos-dc-monstro-do-p%C3%A2ntano-ra%C3%ADzes',
                'link3' => 'https://www.rika.com.br/monstro-do-pantano---raizes-do-mal--1-15006194/p?srsltid=AfmBOoro4Mz9EIyeOFRsNY8ILw6CTnHlvlcdcJ9iaSDeoDjJBYmBdGAd',
                'loja1' => 'Amazon',
                'loja2' => 'Mercado Livre',
                'loja3' => 'Rika Comic Shop',
            ],
            [
                'id' => 11,
                'titulo' => 'Gideon Falls - O Celeiro Negro | vol. 1',
                'descricao' => 'A trama acompanha dois personagens principais: Norton Sinclair, um jovem recluso obcecado por encontrar \"artefatos\" no lixo que ele acredita estarem ligados a uma conspiração; e o Padre Fred, um sacerdote com um passado conturbado que é transferido para a pequena cidade de Gideon Falls, repleta de segredos obscuros. As vidas de ambos se entrelaçam em torno da misteriosa lenda do Celeiro Negro, uma estrutura enigmática que aparece e reaparece ao longo da história, trazendo morte e loucura em seu rastro.',
                'generos' => 'Terror / Suspense',
                'autor' => 'Jeff Lemire',
                'lancamento' => '2021-03-10',
                'imagens' => 'gideon_falls.jpg',
                'link1' => 'https://www.amazon.com.br/Gideon-Falls-Jeff-Lemire/dp/8569032412',
                'link2' => 'https://www.estantevirtual.com.br/livro/gideon-falls-volume-1-068-5114-000-BK',
                'link3' => 'https://produto.mercadolivre.com.br/MLB-4671571570-livro-gideon-falls-volume-1-o-celeiro-negro-_JM',
                'loja1' => 'Amazon',
                'loja2' => 'Estante Virtual',
                'loja3' => 'Mercado Livre',
            ],
            [
                'id' => 12,
                'titulo' => 'Batman Amaldiçoado ',
                'descricao' => 'Após a misteriosa morte do Coringa, Batman acorda ferido e desorientado. Conforme investiga o caso, ele começa a ser assombrado por visões sombrias e eventos sobrenaturais. Para desvendar esse mistério, o Cavaleiro das Trevas contará com a ajuda de John Constantine e outros personagens do lado oculto do Universo DC. Uma história madura, repleta de suspense e terror psicológico.',
                'generos' => 'Suspense / Terror Psicológico / Sobrenatural',
                'autor' => 'Brian Azzarello',
                'lancamento' => '2019-07-07',
                'imagens' => 'batman_amaldicoado.png',
                'link1' => 'https://www.amazon.com.br/Batman-Amaldi%C3%A7oado-Brian-Azzarello/dp/8542625420',
                'link2' => 'https://www.estantevirtual.com.br/livro/batman-amaldicoado-HZR-9088-000',
                'link3' => 'https://comicboom.com.br/produto/batman-amaldicoado/',
                'loja1' => 'Amazon',
                'loja2' => 'Estante Virtual',
                'loja3' => 'Comic Boom',
            ],
        ]);
    }
}

